version: '3'

services:
  app_1: &app
    build:
      context: .
      dockerfile: compose/app/Dockerfile
    command: gunicorn main:app -b 0.0.0.0:1111
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app:/app

  app_2:
    <<: *app
    command: gunicorn main:app -b 0.0.0.0:2222

  app_3:
    <<: *app
    command: gunicorn main:app -b 0.0.0.0:33333

  nginx:
    build:
      context: .
      dockerfile: compose/nginx/Dockerfile
    sysctls:
      net.core.somaxconn: '511'
    ports:
      - 80:80
    depends_on:
      - app_1
      - app_2
      - app_3
