version: '3'

services:
  app_1: &app
    build:
      context: .
      dockerfile: compose/app/Dockerfile
    command: gunicorn main:app -b 0.0.0.0:1111
    volumes:
      - ./app:/app

  app_2:
    <<: *app
    command: gunicorn main:app -b 0.0.0.0:2222
    depends_on:
      - app_1

  app_3:
    <<: *app
    command: gunicorn main:app -b 0.0.0.0.:33333
    depends_on:
      - app_2

  nginx:
    build:
      context: .
      dockerfile: compose/nginx/Dockerfile
    sysctls:
      net.core.somaxconn: '511'
    depends_on:
      - app_3
